### ISSUE TITLE
자료 이미지 백업

### ISSUE THREAD

**Issue by KimDoubleB** [mash-up-kr/S3A#23]
자료 이미지 백업하는 공간

**Comment by KimDoubleB** [comment]
![image](https://user-images.githubusercontent.com/37873745/227191031-32e6b272-1c36-4e8c-b66f-de73f2abc620.png)

**Comment by KimDoubleB** [comment]
<img width="967" alt="스크린샷 2023-04-06 오후 8 15 07" src="https://user-images.githubusercontent.com/37873745/230364739-d7b48d9a-c431-455c-9434-5bdb3d8936d2.png">

**Comment by KimDoubleB** [comment]
![image](https://user-images.githubusercontent.com/37873745/231746591-3884617b-6b8e-4434-8c91-7b176de69ab1.png)

**Comment by bohub12** [comment]
![image](https://user-images.githubusercontent.com/75842372/235367466-3897a036-7612-4876-8ffd-d02063893578.png)

**Comment by bohub12** [comment]
![image](https://user-images.githubusercontent.com/75842372/235367861-5ef31425-dfa7-46d3-bb81-571e2b6a7168.png)
